language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: bryanbenavente
      token:
        secure: 0c46fac8351c54e114a605e19f9db3a520e79373

jdk:
  - openjdk8

script:
  - mvn clean verify sonar:sonar -Pcoverage 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
